spring:
  datasource:
    url: jdbc:mysql://39.104.168.30:3306/crawl?characterEncoding=utf-8
    username: root
    password: bdMySQL@2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true