spring:
  datasource:
    url: jdbc:mysql://localhost/initial-value-generator
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
#    hibernate:
#      ddl-auto: create